const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
let staticMode=false;try{staticMode=sessionStorage.getItem('how-i-see-static')==='true'}catch{}
const status=document.getElementById('contact-status');const drop=document.getElementById('stamp-drop');const stamps=[...document.querySelectorAll('.stamp-options .topic-stamp')];const switchButton=document.querySelector('.motion-switch');
const prefersStill=()=>staticMode||reducedMotion.matches;
function syncMotion(){document.body.dataset.static=String(staticMode);document.documentElement.classList.toggle('static-mode',staticMode);switchButton.setAttribute('aria-pressed',String(staticMode));switchButton.textContent=staticMode?'静态模式 · 开':'静态模式';}
switchButton.addEventListener('click',()=>{staticMode=!staticMode;try{sessionStorage.setItem('how-i-see-static',String(staticMode))}catch{}document.getAnimations().forEach(a=>a.cancel());syncMotion()});syncMotion();
if(!prefersStill()){document.querySelector('.profile-book').animate([{opacity:0,transform:'translateY(24px) rotate(-8deg)'},{opacity:1,transform:getComputedStyle(document.querySelector('.profile-book')).transform}],{duration:650,easing:'cubic-bezier(.2,.8,.2,1)'});document.querySelector('.postcard').animate([{opacity:0,transform:'translateY(30px) rotate(4deg)'},{opacity:1,transform:getComputedStyle(document.querySelector('.postcard')).transform}],{duration:650,delay:100,easing:'cubic-bezier(.2,.8,.2,1)',fill:'backwards'});}
let selectedTopic='';let ignoreClickUntil=0;
window.addEventListener('how-language-change',()=>{const selected=stamps.find(b=>b.dataset.topic===selectedTopic);if(selected)chooseStamp(selected)});
function chooseStamp(button){selectedTopic=button.dataset.topic;stamps.forEach(s=>s.setAttribute('aria-pressed',String(s===button)));const copy=document.createElement('div');copy.className=button.className;copy.innerHTML=button.innerHTML;copy.setAttribute('aria-hidden','true');drop.replaceChildren(copy);drop.setAttribute('aria-label',`已选邮票：${selectedTopic}`);document.getElementById('selected-topic').textContent=`来信主题：${selectedTopic}`;status.textContent=`已贴好「${selectedTopic}」。可以继续写信。`;if(!prefersStill())copy.animate([{transform:'translateY(-12px) rotate(9deg)',opacity:.4},{transform:'translateY(0) rotate(-4deg)',opacity:1}],{duration:320,easing:'cubic-bezier(.2,.8,.2,1)'});}
stamps.forEach(button=>{button.addEventListener('click',()=>{if(performance.now()<ignoreClickUntil)return;chooseStamp(button)});let drag=null;
 button.addEventListener('pointerdown',event=>{if(event.button!==0)return;drag={x:event.clientX,y:event.clientY,moved:false,ghost:null,pointerId:event.pointerId};button.setPointerCapture(event.pointerId)});
 button.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.pointerId)return;const distance=Math.hypot(event.clientX-drag.x,event.clientY-drag.y);if(distance>7&&!drag.moved){drag.moved=true;drag.ghost=button.cloneNode(true);drag.ghost.removeAttribute('aria-pressed');drag.ghost.removeAttribute('data-topic');drag.ghost.tabIndex=-1;drag.ghost.setAttribute('aria-hidden','true');drag.ghost.classList.add('stamp-ghost');document.body.append(drag.ghost);button.style.opacity='.45'}if(!drag.moved)return;drag.ghost.style.transform=`translate(${event.clientX-45}px,${event.clientY-45}px) rotate(6deg)`;const rect=drop.getBoundingClientRect();drop.classList.toggle('drag-over',event.clientX>=rect.left-15&&event.clientX<=rect.right+15&&event.clientY>=rect.top-15&&event.clientY<=rect.bottom+15)});
 function clearDrag(){if(drag?.ghost)drag.ghost.remove();drag=null;button.style.opacity='';drop.classList.remove('drag-over')}
 button.addEventListener('pointerup',event=>{if(!drag)return;if(drag.moved){ignoreClickUntil=performance.now()+400;const rect=drop.getBoundingClientRect();if(event.clientX>=rect.left-15&&event.clientX<=rect.right+15&&event.clientY>=rect.top-15&&event.clientY<=rect.bottom+15)chooseStamp(button);else status.textContent='把邮票放到明信片右上角，或直接点击邮票。'}clearDrag()});button.addEventListener('pointercancel',clearDrag);button.addEventListener('lostpointercapture',clearDrag);
});
const form=document.getElementById('postcard-form');const message=document.getElementById('message');const nameInput=document.getElementById('sender-name');const emailInput=document.getElementById('sender-email');
message.addEventListener('input',()=>document.getElementById('character-count').textContent=`${message.value.length} / 3000`);
function draft(){const name=nameInput.value.trim();const email=emailInput.value.trim();const note=message.value.trim();const english=window.HowISeeLanguage?.isEnglish();const topic=window.HowISeeLanguage?.translate(selectedTopic)||selectedTopic;if(english)return{subject:`Jinghan Wang · ${topic||'A little letter'}`,body:`Hello Jinghan,\n\n${note}\n\n${name?`From: ${name}\n`:''}${email?`Reply to: ${email}\n`:''}${topic?`Topic: ${topic}\n`:''}`};return{subject:`Jinghan Wang · ${selectedTopic||'一封来信'}`,body:`靖函，你好：\n\n${note}\n\n${name?`来自：${name}\n`:''}${email?`回信地址：${email}\n`:''}${selectedTopic?`来信主题：${selectedTopic}\n`:''}`};}
async function copyText(text,success){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text)}else{const helper=document.createElement('textarea');helper.value=text;helper.style.position='fixed';helper.style.opacity='0';document.body.append(helper);helper.select();const copied=document.execCommand('copy');helper.remove();if(!copied)throw Error('copy unavailable')}document.getElementById('copy-fallback').hidden=true;status.textContent=success}catch{const area=document.getElementById('copy-text');document.getElementById('copy-fallback').hidden=false;area.value=text;area.focus();area.select();status.textContent='自动复制不可用，下方文字可以手动复制。'}}
document.getElementById('copy-email').addEventListener('click',()=>copyText('wangjh2923@mails.jlu.edu.cn','邮箱已复制，可以粘贴到你常用的邮件应用。'));
document.getElementById('copy-letter').addEventListener('click',()=>{if(!form.reportValidity())return;if(!message.value.trim()){message.focus();status.textContent='先写下你想说的话。';return}const d=draft();const en=window.HowISeeLanguage?.isEnglish();copyText(`${en?'To':'收件人'}：wangjh2923@mails.jlu.edu.cn\n${en?'Subject':'主题'}：${d.subject}\n\n${d.body}`,'信件内容已复制，尚未发送。')});
form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;if(!message.value.trim()){message.focus();status.textContent='先写下你想说的话。';return}const d=draft();const href=`mailto:wangjh2923@mails.jlu.edu.cn?subject=${encodeURIComponent(d.subject)}&body=${encodeURIComponent(d.body)}`;status.textContent='已尝试打开邮件应用，尚未发送。若没有打开，请使用“复制这封信”。';const a=document.createElement('a');a.href=href;a.hidden=true;document.body.append(a);a.click();a.remove()});
