(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const bi=(z,e)=>`<span class="bi"><span lang="zh-CN">${z}</span><span lang="en">${e}</span></span>`;
let english=false,staticMode=false;try{english=localStorage.getItem('how-i-see-language')==='en';staticMode=sessionStorage.getItem('how-i-see-static')==='true'}catch{}
const reduce=matchMedia('(prefers-reduced-motion:reduce)'),still=()=>staticMode||reduce.matches;
const legacy=window.HowISeeLanguage;
function language(en){english=en;document.documentElement.dataset.language=en?'en':'mixed';document.documentElement.lang=en?'en':'zh-CN';try{localStorage.setItem('how-i-see-language',en?'en':'mixed')}catch{}if(legacy)legacy.set(en);else window.dispatchEvent(new CustomEvent('how-language-change',{detail:{english:en}}));$$('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.lang==='en')===en)));document.title=document.title.replace('How I See —','Jinghan Wang —');window.ScrollTrigger?.refresh()}
if(!legacy)window.HowISeeLanguage={isEnglish:()=>english,set:language,translate:s=>s,refresh:()=>{}};
language(english);
$$('.language-mount').forEach(mount=>{
mount.innerHTML=`<div class="language-window"><button class="window-trigger" aria-label="Reading language" aria-expanded="false">×</button><div class="cabin-shell"><div class="cabin-view"><div class="window-shade"><strong>MIX</strong></div><input class="shade-control" type="range" min="0" max="100" value="0" aria-label="Lift for English; lower for bilingual" tabindex="-1"></div></div><div class="window-controls"><button data-lang="mixed" tabindex="-1">中 / MIX</button><button data-lang="en" tabindex="-1">EN</button><p>${bi('上拉英文 · 下拉中英','Lift for EN · lower for MIX')}</p></div></div>`;
const win=$('.language-window',mount),trigger=$('.window-trigger',win),range=$('input',win),view=$('.cabin-view',win);let timer,drag=null;
function paint(v){win.style.setProperty('--shade',v*.88);range.value=v;range.setAttribute('aria-valuetext',v>=50?'English':'Bilingual')}
function open(){clearTimeout(timer);win.classList.add('open');trigger.setAttribute('aria-expanded','true');range.tabIndex=0;$$('[data-lang]',win).forEach(b=>b.tabIndex=0)}
function close(){if(drag)return;win.classList.remove('open');trigger.setAttribute('aria-expanded','false');range.tabIndex=-1;$$('[data-lang]',win).forEach(b=>b.tabIndex=-1)}
function later(){clearTimeout(timer);timer=setTimeout(()=>{if(!win.matches(':hover')&&!win.querySelector(':focus-visible'))close()},260)}
win.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')open()});win.addEventListener('pointerleave',later);win.addEventListener('focusin',open);win.addEventListener('focusout',later);
trigger.addEventListener('click',()=>{if(win.classList.contains('open')&&trigger.dataset.touched==='1'){trigger.dataset.touched='0';trigger.blur();close()}else{trigger.dataset.touched='1';open()}});
$$('[data-lang]',win).forEach(b=>b.addEventListener('click',()=>{language(b.dataset.lang==='en');paint(english?100:0)}));
range.addEventListener('input',()=>paint(+range.value));range.addEventListener('change',()=>{language(+range.value>=50);paint(english?100:0)});
view.addEventListener('pointerdown',e=>{if(!win.classList.contains('open')||e.button!==0)return;e.preventDefault();drag={id:e.pointerId,y:e.clientY,v:+range.value,h:view.getBoundingClientRect().height};view.setPointerCapture(e.pointerId)});
view.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;paint(Math.max(0,Math.min(100,drag.v+(drag.y-e.clientY)/drag.h*140)))});
function finish(cancel=false){if(!drag)return;drag=null;if(!cancel)language(+range.value>=50);paint(english?100:0);later()}
view.addEventListener('pointerup',()=>finish());view.addEventListener('pointercancel',()=>finish(true));view.addEventListener('lostpointercapture',()=>finish(true));
win.addEventListener('keydown',e=>{if(e.key==='Escape'){trigger.focus();trigger.blur();close()}});document.addEventListener('pointerdown',e=>{if(!win.contains(e.target)){close();trigger.dataset.touched='0'}});
window.addEventListener('how-language-change',()=>paint(english?100:0));paint(english?100:0);
});language(english);
$('.menu-toggle')?.addEventListener('click',e=>{const nav=$('#main-nav'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});$$('#main-nav a').forEach(a=>a.addEventListener('click',()=>{$('#main-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}));
let entrancePromise=Promise.resolve();let motionContext;function motion(){motionContext?.revert();document.documentElement.classList.toggle('static-mode',staticMode);$$('.still-toggle').forEach(b=>b.setAttribute('aria-pressed',String(staticMode)));if(!window.gsap||!window.ScrollTrigger||still()){const opening=$('.opening');if(opening)opening.style.background='#fff';return}gsap.registerPlugin(ScrollTrigger);motionContext=gsap.context(()=>{
const opening=$('.opening');if(opening){gsap.to(opening,{backgroundColor:'#c7dfd2',ease:'none',scrollTrigger:{trigger:opening,start:'top -15%',end:'bottom 80%',scrub:true}});gsap.to('.opening-center',{y:-45,opacity:.35,ease:'none',scrollTrigger:{trigger:opening,start:'top -10%',end:'bottom 40%',scrub:true}});$$('.orbit-item').forEach((a,i)=>gsap.to(a,{x:i%2?25:-25,y:i<3?-45:35,opacity:.25,ease:'none',scrollTrigger:{trigger:opening,start:'top -10%',end:'bottom 40%',scrub:true}}))}
$$('.chapter-heading').forEach(h=>{const cap=innerWidth<700?1.35:Math.min(2.1,(innerWidth*.91)/h.offsetWidth);gsap.fromTo(h,{scale:cap,x:innerWidth<700?12:35,y:35},{scale:1,x:0,y:0,ease:'none',scrollTrigger:{trigger:h.closest('.chapter-arrival'),start:'top 95%',end:'top 20%',scrub:true,invalidateOnRefresh:true}})});
$$('.pink-mark').forEach(h=>gsap.fromTo(h,{opacity:.48},{opacity:1,ease:'none',scrollTrigger:{trigger:h,start:'top 92%',end:'top 62%',scrub:true}}));
});}
$$('.still-toggle').forEach(b=>b.addEventListener('click',()=>{staticMode=!staticMode;try{sessionStorage.setItem('how-i-see-static',String(staticMode))}catch{}if(staticMode){document.getAnimations().forEach(a=>a.finish());$$('.orbit-item,.opening-center').forEach(a=>a.style.opacity='1')}motion();drawTears()}));
reduce.addEventListener('change',()=>{motion();drawTears()});document.fonts.ready.then(()=>entrancePromise).then(()=>{motion();window.ScrollTrigger?.refresh()});addEventListener('how-language-change',()=>{requestAnimationFrame(motion)});
// Entrance starts by itself. Reading never depends on a hover or a drag.
const orbit=$$('.orbit-item');
if(orbit.length&&!still()){
 let played=false;
 const showOpening=()=>{if(played||still())return;played=true;const stage=$('.opening-stage');stage.dataset.entrance='playing';
 orbit.forEach((a,i)=>{const final=getComputedStyle(a).transform;const anim=a.animate([{opacity:0,transform:'translate(-50%,-50%) scale(.08)'},{opacity:1,transform:final}],{duration:1200,delay:180+i*85,easing:'cubic-bezier(.16,.85,.24,1.1)',fill:'backwards'});if(i===orbit.length-1)entrancePromise=anim.finished.catch(()=>{}).then(()=>{stage.dataset.entrance='complete';window.ScrollTrigger?.refresh()})});
 $('.opening-center').animate([{opacity:0,scale:'.92'},{opacity:1,scale:'1'}],{duration:700,easing:'ease-out'});
 };
 const openingObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting&&e.intersectionRatio>.45)){document.fonts.ready.then(showOpening);openingObserver.disconnect()}},{threshold:[.45,.6]});openingObserver.observe($('.opening-stage'));
}
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)$$('#main-nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}),{rootMargin:'-15% 0px -65% 0px'});$$('main>section[id]').forEach(s=>sectionObserver.observe(s));
// Keep the reading position when following an object to a separate page.
document.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&a.origin===location.origin&&a.pathname!==location.pathname){try{sessionStorage.setItem('scroll:'+location.pathname,String(scrollY))}catch{}}});
addEventListener('pageshow',e=>{if(e.persisted)return;const nav=performance.getEntriesByType('navigation')[0];if(nav?.type==='back_forward'){try{const y=+sessionStorage.getItem('scroll:'+location.pathname);requestAnimationFrame(()=>scrollTo(0,y))}catch{}}});
const conversation=$('.conversation');function perspective(view){if(!conversation)return;conversation.dataset.perspective=view;$$('[data-view]',conversation).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));$('.perspective-switch',conversation).innerHTML=view==='speaker'?bi('换到听的人 ↔','Switch to the listener ↔'):bi('换到说的人 ↔','Switch to the speaker ↔');$('.perspective-note',conversation).innerHTML=view==='speaker'?bi('此刻站在表达者一侧：你会怎样回应？一句话的意图，并不能替听者决定感受。','From the speaker’s side: what would you say? Intention alone cannot determine how a response is received.'):bi('换到接受者一侧：你更愿意听到什么？同一句回应，可以留下不同的理解空间。','From the listener’s side: what would you welcome? The same response can leave room for different readings.')}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>perspective(b.dataset.view)));$('.perspective-switch')?.addEventListener('click',()=>perspective(conversation.dataset.perspective==='speaker'?'listener':'speaker'));
const makeInfo={script:['文字，要经过一次排练。','Words need a rehearsal.','原创剧本创作与打磨，协同团队排演，参与面向 400 余名观众的课程公演。','Writing, revising and rehearsing an original script with the team for a course performance attended by over 400 people.'],editing:['写进去，也重新组织。','Write, and give it structure.','独立撰写导言与理论升华章节，整合团队素材，完成全文统稿与校审。','I independently wrote the introduction and theoretical discussion, integrated the team’s material, and edited and proofread the full text.'],brand:['鲜果 → 体验 → 品牌','Fruit → Experience → Brand','市场与客群研究，连接采摘节、亲子研学与节日礼盒。一份农旅融合策划，三层相互关联的问题。','Market and audience research connects picking festivals, family learning and seasonal gifts: three layers of an agritourism strategy.']};
$$('[data-make]').forEach(b=>b.addEventListener('click',()=>{const panel=$('#make-panel'),same=b.getAttribute('aria-expanded')==='true';$$('[data-make]').forEach(x=>{x.setAttribute('aria-expanded','false');x.classList.remove('activated')});panel.hidden=same;if(same){window.ScrollTrigger?.refresh();return}b.setAttribute('aria-expanded','true');b.classList.add('activated');const d=makeInfo[b.dataset.make];panel.innerHTML=`<button class="panel-close" aria-label="Close project">×</button><h4>${bi(d[0],d[1])}</h4><p>${bi(d[2],d[3])}</p><a class="text-link" href="project.html?id=${b.dataset.make}">${bi('打开项目档案','Open the project')} ↗</a>`;$('.panel-close',panel).addEventListener('click',()=>{b.click();b.focus()});if(!still())panel.animate([{opacity:0,transform:'translateY(-10px)'},{opacity:1,transform:'translateY(0)'}],{duration:420,easing:'ease-out'});window.ScrollTrigger?.refresh()}));
const notesVolume=$('.notes-volume'),notesFront=$('.notes-front'),notesPage=$('.notes-page');
function toggleNotes(){const open=notesVolume.classList.toggle('is-open');notesFront.setAttribute('aria-expanded',String(open));notesPage.inert=!open}
notesFront?.addEventListener('click',toggleNotes);
notesPage?.addEventListener('click',e=>{if(!e.target.closest('a,button')&&notesVolume.classList.contains('is-open'))toggleNotes()});
notesVolume?.addEventListener('keydown',e=>{if(e.key==='Escape'&&notesVolume.classList.contains('is-open')){toggleNotes();notesFront.focus()}});
if(notesPage)notesPage.inert=true;

const camera=$('.camera-trigger');let printIndex=0;const colours=[['#c7dfd2','一小片薄荷绿','A little mint green'],['#d7a0b0','留下来的粉色','A pink worth keeping'],['#829aa4','蓝色的停顿','A pause in blue']];
camera?.addEventListener('click',async()=>{if(camera.disabled)return;camera.disabled=true;const p=$('.printed-photo'),sheet=$('.eject-paper'),d=colours[++printIndex%colours.length];$('.print-image').style.background=d[0];p.querySelector('small').textContent='COLOUR STUDY / 0'+(printIndex%colours.length+1);p.querySelector('span').innerHTML=bi(d[1],d[2]);sheet.style.backgroundColor=d[0];if(still()){camera.disabled=false;return}p.style.opacity='0';const flash=$('.camera-flash').animate([{opacity:0},{opacity:.9,offset:.25},{opacity:0}],{duration:240});await flash.finished;await sheet.animate([{transform:'translateY(154px)'},{transform:'translateY(0)'}],{duration:1050,easing:'cubic-bezier(.4,0,.4,1)',fill:'forwards'}).finished;const source=sheet.getBoundingClientRect(),dest=p.getBoundingClientRect();p.style.opacity='1';sheet.getAnimations().forEach(a=>a.cancel());await p.animate([{transform:`translate(${source.left-dest.left}px,${source.top-dest.top}px) rotate(0deg) scale(.83)`},{transform:'translate(0,-5px) rotate(9deg)',offset:.83},{transform:'translate(0,0) rotate(8deg)'}],{duration:720,easing:'cubic-bezier(.2,.8,.2,1)'}).finished;camera.disabled=false});
function drawTears(){window.dispatchEvent(new Event('v6-motion-change'))}
const favourites={harry:['赫敏与她的世界','Hermione’s world','我最欣赏赫敏，她的努力、坚强、聪明。','What I most admire about Hermione is her hard work, strength and intelligence.'],camera:['我的 mini 99','My mini 99','喜欢相机，也喜欢照片变成一个可以拿在手里的东西。高中使用的 Sony ZV-1，则留在了另一篇回忆里。','I like cameras, and photographs that become something you can hold. The Sony ZV-1 I used in high school belongs to another piece of writing.','note.html?id=camera'],music:['最近在听','On repeat','先放这一年的 Replay，之后还会继续更新。','My Replay for this year, with more to come.','https://music.apple.com/cn/playlist/replay-2024/pl.rp-WoWxuBjEnM5a?l=en'],nine:['九号秘事','Inside No. 9','每一集都是不同的世界、不同的表达形式。我喜欢它讲故事的方式，也喜欢不同故事里再次出现的线索：数字九、黄铜兔子……','Each episode is a different world, with a different form. I like the way it tells stories, and the clues that recur across them: the number nine, the brass hare…'],groundhog:['土拨鼠之日','Groundhog Day','如果日复一日，生活没有改变，我们会怎么做？这个故事留给我的，是对自己的生活的回望。','If life repeated, day after day, what would we do? The story makes me turn back towards my own life.'],editing:['写下来的事','Things written down','我会观察镜头、台词和叙事的顺序，也会反过来问：自己的判断从哪里来？','I notice shots, dialogue and narrative order. Then I ask: where do my own judgements come from?','note.html?id=dear-you']};
const dialog=$('.favourite-dialog');let favouriteOpener;
$$('[data-favourite]').forEach(b=>b.addEventListener('click',()=>{favouriteOpener=b;const key=b.dataset.favourite,d=favourites[key],art=$('.tray-art',b).innerHTML;$('#favourite-content').innerHTML=`<div class="favourite-body"><div class="favourite-art">${art}</div><div><span class="eyebrow">A FEW OF MY FAVOURITES</span><h2 id="favourite-title">${bi(d[0],d[1])}</h2><p>${bi(d[2],d[3])}</p>${key==='groundhog'?'<blockquote><p>“That about sums it up for me.”</p><small>Ralph · Groundhog Day</small></blockquote>':''}${d[4]?`<a class="text-link" href="${d[4]}" ${key==='music'?'target="_blank" rel="noopener"':''}>${key==='music'?'Open in Apple Music':bi('继续读下去','Read on')} ↗</a>`:''}</div></div>`;dialog.showModal();if(!still())dialog.animate([{opacity:0,transform:'translateY(15px) scale(.97)'},{opacity:1,transform:'none'}],{duration:320,easing:'ease-out'})}));
$('.dialog-close')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog?.addEventListener('close',()=>favouriteOpener?.focus());
// Colour-book study; no borrowed photographs are presented as personal work.
const spread=$('.photo-spread');if(spread){let page=0;const pages=[['#8e423b','停留的锈红','A lingering red','从一处颜色开始，看它怎样改变周围的光。','Start with one colour, and notice how it changes the light around it.'],['#bd7357','暖色之间','Between warm tones','不急着找故事，先看色彩之间的关系。','Before looking for a story, look at the relationship between colours.'],['#d4b858','一点明亮','A little brightness','把目光停在一个很小的地方。','Let your gaze rest on one small place.'],['#829487','绿色的间隙','A space in green','留一点空白，让下一张照片有地方呼吸。','Leave some space for the next photograph to breathe.'],['#829aa4','最后一片蓝','One last blue','结束之前，再看一遍。','Before you finish, look once more.']];function show(){const d=pages[page];$('.colour-sample').style.background=d[0];$('.photo-spread h2').innerHTML=bi(d[1],d[2]);$('.photo-spread .colour-caption').innerHTML=bi(d[3],d[4]);$('.page-count').textContent=`${page+1} / 5`;$$('[data-colour]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.colour===page)));if(!still())spread.animate([{opacity:.4,transform:'rotateY(-4deg)'},{opacity:1,transform:'none'}],{duration:350,easing:'ease-out'})}$$('[data-page]').forEach(b=>b.addEventListener('click',()=>{page=(page+(b.dataset.page==='next'?1:4))%5;show()}));$$('[data-colour]').forEach(b=>b.addEventListener('click',()=>{page=+b.dataset.colour;show()}));document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,button,a'))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){page=(page+(e.key==='ArrowRight'?1:4))%5;show()}});show()}
})();
